// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart_items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const clearCartItemsByUser = `-- name: ClearCartItemsByUser :exec
UPDATE cart_items
SET is_active = false,
    updated_at = $2
WHERE user_id = $1 AND is_active = true
`

type ClearCartItemsByUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ClearCartItemsByUser(ctx context.Context, arg ClearCartItemsByUserParams) error {
	_, err := q.db.ExecContext(ctx, clearCartItemsByUser, arg.UserID, arg.UpdatedAt)
	return err
}

const deactivateCartItemByUserAndVariant = `-- name: DeactivateCartItemByUserAndVariant :exec
UPDATE cart_items
SET is_active = FALSE,
    updated_at = $3
WHERE user_id = $1
  AND variant_id = $2
  AND is_active = TRUE
`

type DeactivateCartItemByUserAndVariantParams struct {
	UserID    uuid.UUID `json:"user_id"`
	VariantID uuid.UUID `json:"variant_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) DeactivateCartItemByUserAndVariant(ctx context.Context, arg DeactivateCartItemByUserAndVariantParams) error {
	_, err := q.db.ExecContext(ctx, deactivateCartItemByUserAndVariant, arg.UserID, arg.VariantID, arg.UpdatedAt)
	return err
}

const getActiveCartVariantSnapshotsByUserAndVariantIDs = `-- name: GetActiveCartVariantSnapshotsByUserAndVariantIDs :many
SELECT
  -- Cart fields
  ci.id                AS cart_item_id,
  ci.user_id           AS cart_user_id,
  ci.variant_id        AS cart_variant_id,
  ci.required_quantity AS cart_required_quantity,
  ci.is_active         AS cart_is_active,
  ci.created_at        AS cart_created_at,
  ci.updated_at        AS cart_updated_at,

  -- Snapshot fields
  pvs.id                         AS snapshot_id,
  pvs.categoryid,
  pvs.iscategoryarchived,
  pvs.categoryname,
  pvs.sellerid,
  pvs.issellerapproved,
  pvs.issellerarchived,
  pvs.issellerbanned,
  pvs.sellerstorename,
  pvs.productid,
  pvs.isproductapproved,
  pvs.isproductarchived,
  pvs.isproductbanned,
  pvs.producttitle,
  pvs.productdescription,
  pvs.productprimaryimageurl,
  pvs.variantid,
  pvs.isvariantarchived,
  pvs.isvariantinstock,
  pvs.stockamount,
  pvs.color,
  pvs.size,
  pvs.retailprice,
  pvs.hasretaildiscount,
  pvs.retaildiscounttype,
  pvs.retaildiscount,
  pvs.haswholesaleenabled,
  pvs.wholesaleprice,
  pvs.wholesaleminquantity,
  pvs.haswholesalediscount,
  pvs.wholesalediscounttype,
  pvs.wholesalediscount,
  pvs.weight_grams,
  pvs.createdat       AS snapshot_created_at,
  pvs.updatedat       AS snapshot_updated_at

FROM cart_items ci
JOIN product_variant_snapshots pvs
  ON ci.variant_id = pvs.variantid
WHERE
    ci.is_active = true
    AND ci.user_id = $1
    AND ci.variant_id = ANY($2::UUID[])
`

type GetActiveCartVariantSnapshotsByUserAndVariantIDsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	VariantIds []uuid.UUID `json:"variant_ids"`
}

type GetActiveCartVariantSnapshotsByUserAndVariantIDsRow struct {
	CartItemID             uuid.UUID      `json:"cart_item_id"`
	CartUserID             uuid.UUID      `json:"cart_user_id"`
	CartVariantID          uuid.UUID      `json:"cart_variant_id"`
	CartRequiredQuantity   sql.NullInt32  `json:"cart_required_quantity"`
	CartIsActive           bool           `json:"cart_is_active"`
	CartCreatedAt          time.Time      `json:"cart_created_at"`
	CartUpdatedAt          time.Time      `json:"cart_updated_at"`
	SnapshotID             uuid.UUID      `json:"snapshot_id"`
	Categoryid             uuid.UUID      `json:"categoryid"`
	Iscategoryarchived     bool           `json:"iscategoryarchived"`
	Categoryname           string         `json:"categoryname"`
	Sellerid               uuid.UUID      `json:"sellerid"`
	Issellerapproved       bool           `json:"issellerapproved"`
	Issellerarchived       bool           `json:"issellerarchived"`
	Issellerbanned         bool           `json:"issellerbanned"`
	Sellerstorename        string         `json:"sellerstorename"`
	Productid              uuid.UUID      `json:"productid"`
	Isproductapproved      bool           `json:"isproductapproved"`
	Isproductarchived      bool           `json:"isproductarchived"`
	Isproductbanned        bool           `json:"isproductbanned"`
	Producttitle           string         `json:"producttitle"`
	Productdescription     string         `json:"productdescription"`
	Productprimaryimageurl string         `json:"productprimaryimageurl"`
	Variantid              uuid.UUID      `json:"variantid"`
	Isvariantarchived      bool           `json:"isvariantarchived"`
	Isvariantinstock       bool           `json:"isvariantinstock"`
	Stockamount            int32          `json:"stockamount"`
	Color                  string         `json:"color"`
	Size                   string         `json:"size"`
	Retailprice            int64          `json:"retailprice"`
	Hasretaildiscount      bool           `json:"hasretaildiscount"`
	Retaildiscounttype     sql.NullString `json:"retaildiscounttype"`
	Retaildiscount         sql.NullInt64  `json:"retaildiscount"`
	Haswholesaleenabled    bool           `json:"haswholesaleenabled"`
	Wholesaleprice         sql.NullInt64  `json:"wholesaleprice"`
	Wholesaleminquantity   sql.NullInt32  `json:"wholesaleminquantity"`
	Haswholesalediscount   bool           `json:"haswholesalediscount"`
	Wholesalediscounttype  sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount      sql.NullInt64  `json:"wholesalediscount"`
	WeightGrams            int32          `json:"weight_grams"`
	SnapshotCreatedAt      time.Time      `json:"snapshot_created_at"`
	SnapshotUpdatedAt      time.Time      `json:"snapshot_updated_at"`
}

func (q *Queries) GetActiveCartVariantSnapshotsByUserAndVariantIDs(ctx context.Context, arg GetActiveCartVariantSnapshotsByUserAndVariantIDsParams) ([]GetActiveCartVariantSnapshotsByUserAndVariantIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCartVariantSnapshotsByUserAndVariantIDs, arg.UserID, pq.Array(arg.VariantIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveCartVariantSnapshotsByUserAndVariantIDsRow
	for rows.Next() {
		var i GetActiveCartVariantSnapshotsByUserAndVariantIDsRow
		if err := rows.Scan(
			&i.CartItemID,
			&i.CartUserID,
			&i.CartVariantID,
			&i.CartRequiredQuantity,
			&i.CartIsActive,
			&i.CartCreatedAt,
			&i.CartUpdatedAt,
			&i.SnapshotID,
			&i.Categoryid,
			&i.Iscategoryarchived,
			&i.Categoryname,
			&i.Sellerid,
			&i.Issellerapproved,
			&i.Issellerarchived,
			&i.Issellerbanned,
			&i.Sellerstorename,
			&i.Productid,
			&i.Isproductapproved,
			&i.Isproductarchived,
			&i.Isproductbanned,
			&i.Producttitle,
			&i.Productdescription,
			&i.Productprimaryimageurl,
			&i.Variantid,
			&i.Isvariantarchived,
			&i.Isvariantinstock,
			&i.Stockamount,
			&i.Color,
			&i.Size,
			&i.Retailprice,
			&i.Hasretaildiscount,
			&i.Retaildiscounttype,
			&i.Retaildiscount,
			&i.Haswholesaleenabled,
			&i.Wholesaleprice,
			&i.Wholesaleminquantity,
			&i.Haswholesalediscount,
			&i.Wholesalediscounttype,
			&i.Wholesalediscount,
			&i.WeightGrams,
			&i.SnapshotCreatedAt,
			&i.SnapshotUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemByUserAndVariant = `-- name: GetCartItemByUserAndVariant :one
SELECT
  id,
  user_id,
  variant_id,
  required_quantity,
  is_active,
  created_at,
  updated_at
FROM cart_items
WHERE
  user_id = $1
  AND variant_id = $2
`

type GetCartItemByUserAndVariantParams struct {
	UserID    uuid.UUID `json:"user_id"`
	VariantID uuid.UUID `json:"variant_id"`
}

func (q *Queries) GetCartItemByUserAndVariant(ctx context.Context, arg GetCartItemByUserAndVariantParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByUserAndVariant, arg.UserID, arg.VariantID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VariantID,
		&i.RequiredQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (
  id,
  user_id,
  variant_id,
  required_quantity,
  is_active,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCartItemParams struct {
	ID               uuid.UUID     `json:"id"`
	UserID           uuid.UUID     `json:"user_id"`
	VariantID        uuid.UUID     `json:"variant_id"`
	RequiredQuantity sql.NullInt32 `json:"required_quantity"`
	IsActive         bool          `json:"is_active"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem,
		arg.ID,
		arg.UserID,
		arg.VariantID,
		arg.RequiredQuantity,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveVariantIDsByUser = `-- name: ListActiveVariantIDsByUser :many
SELECT variant_id
FROM cart_items
WHERE
    is_active = true
    AND user_id = $1
`

func (q *Queries) ListActiveVariantIDsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listActiveVariantIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var variant_id uuid.UUID
		if err := rows.Scan(&variant_id); err != nil {
			return nil, err
		}
		items = append(items, variant_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateCartItemByID = `-- name: ReactivateCartItemByID :exec
UPDATE cart_items
SET
    required_quantity = $1,
    is_active = $2,
    updated_at = $3
WHERE id = $4
`

type ReactivateCartItemByIDParams struct {
	RequiredQuantity sql.NullInt32 `json:"required_quantity"`
	IsActive         bool          `json:"is_active"`
	UpdatedAt        time.Time     `json:"updated_at"`
	ID               uuid.UUID     `json:"id"`
}

func (q *Queries) ReactivateCartItemByID(ctx context.Context, arg ReactivateCartItemByIDParams) error {
	_, err := q.db.ExecContext(ctx, reactivateCartItemByID,
		arg.RequiredQuantity,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCartItemQuantityByID = `-- name: UpdateCartItemQuantityByID :exec
UPDATE cart_items
SET
    required_quantity = $1,
    is_active = $2,
    updated_at = $3
WHERE
    id = $4
`

type UpdateCartItemQuantityByIDParams struct {
	RequiredQuantity sql.NullInt32 `json:"required_quantity"`
	IsActive         bool          `json:"is_active"`
	UpdatedAt        time.Time     `json:"updated_at"`
	ID               uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateCartItemQuantityByID(ctx context.Context, arg UpdateCartItemQuantityByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItemQuantityByID,
		arg.RequiredQuantity,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCartQuantityForUser = `-- name: UpdateCartQuantityForUser :exec
UPDATE cart_items
SET
  required_quantity = $1,
  updated_at = $2
WHERE
  user_id = $3
  AND variant_id = $4
`

type UpdateCartQuantityForUserParams struct {
	RequiredQuantity sql.NullInt32 `json:"required_quantity"`
	UpdatedAt        time.Time     `json:"updated_at"`
	UserID           uuid.UUID     `json:"user_id"`
	VariantID        uuid.UUID     `json:"variant_id"`
}

func (q *Queries) UpdateCartQuantityForUser(ctx context.Context, arg UpdateCartQuantityForUserParams) error {
	_, err := q.db.ExecContext(ctx, updateCartQuantityForUser,
		arg.RequiredQuantity,
		arg.UpdatedAt,
		arg.UserID,
		arg.VariantID,
	)
	return err
}
