// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: checkout_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertCheckoutSession = `-- name: InsertCheckoutSession :one
INSERT INTO checkout_sessions (
    id,
    user_id,
    subtotal,
    total_weight_grams,
    delivery_charge,
    total_payable,
    shipping_address_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    user_id,
    subtotal,
    total_weight_grams,
    delivery_charge,
    total_payable,
    shipping_address_id,
    created_at
`

type InsertCheckoutSessionParams struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Subtotal          string         `json:"subtotal"`
	TotalWeightGrams  int32          `json:"total_weight_grams"`
	DeliveryCharge    sql.NullString `json:"delivery_charge"`
	TotalPayable      string         `json:"total_payable"`
	ShippingAddressID uuid.NullUUID  `json:"shipping_address_id"`
	CreatedAt         time.Time      `json:"created_at"`
}

func (q *Queries) InsertCheckoutSession(ctx context.Context, arg InsertCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRowContext(ctx, insertCheckoutSession,
		arg.ID,
		arg.UserID,
		arg.Subtotal,
		arg.TotalWeightGrams,
		arg.DeliveryCharge,
		arg.TotalPayable,
		arg.ShippingAddressID,
		arg.CreatedAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subtotal,
		&i.TotalWeightGrams,
		&i.DeliveryCharge,
		&i.TotalPayable,
		&i.ShippingAddressID,
		&i.CreatedAt,
	)
	return i, err
}
