// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: checkout_items.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertCheckoutItem = `-- name: InsertCheckoutItem :one
INSERT INTO checkout_items (
    id,
    checkout_session_id,
    user_id,
    seller_id,
    seller_store_name,  -- ✅ New field
    category_id,
    category_name,
    product_id,
    product_title,
    product_description,
    product_primary_image_url,
    variant_id,
    color,
    size,
    buying_mode,
    unit_price,
    has_discount,
    discount_type,
    discount_value,
    required_quantity,
    weight_grams,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5, -- ✅ New arg
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
RETURNING
    id,
    checkout_session_id,
    user_id,
    seller_id,
    seller_store_name,  -- ✅ New return field
    category_id,
    category_name,
    product_id,
    product_title,
    product_description,
    product_primary_image_url,
    variant_id,
    color,
    size,
    buying_mode,
    unit_price,
    has_discount,
    discount_type,
    discount_value,
    required_quantity,
    weight_grams,
    created_at
`

type InsertCheckoutItemParams struct {
	ID                     uuid.UUID `json:"id"`
	CheckoutSessionID      uuid.UUID `json:"checkout_session_id"`
	UserID                 uuid.UUID `json:"user_id"`
	SellerID               uuid.UUID `json:"seller_id"`
	SellerStoreName        string    `json:"seller_store_name"`
	CategoryID             uuid.UUID `json:"category_id"`
	CategoryName           string    `json:"category_name"`
	ProductID              uuid.UUID `json:"product_id"`
	ProductTitle           string    `json:"product_title"`
	ProductDescription     string    `json:"product_description"`
	ProductPrimaryImageUrl string    `json:"product_primary_image_url"`
	VariantID              uuid.UUID `json:"variant_id"`
	Color                  string    `json:"color"`
	Size                   string    `json:"size"`
	BuyingMode             string    `json:"buying_mode"`
	UnitPrice              string    `json:"unit_price"`
	HasDiscount            bool      `json:"has_discount"`
	DiscountType           string    `json:"discount_type"`
	DiscountValue          string    `json:"discount_value"`
	RequiredQuantity       int32     `json:"required_quantity"`
	WeightGrams            int32     `json:"weight_grams"`
	CreatedAt              time.Time `json:"created_at"`
}

type InsertCheckoutItemRow struct {
	ID                     uuid.UUID `json:"id"`
	CheckoutSessionID      uuid.UUID `json:"checkout_session_id"`
	UserID                 uuid.UUID `json:"user_id"`
	SellerID               uuid.UUID `json:"seller_id"`
	SellerStoreName        string    `json:"seller_store_name"`
	CategoryID             uuid.UUID `json:"category_id"`
	CategoryName           string    `json:"category_name"`
	ProductID              uuid.UUID `json:"product_id"`
	ProductTitle           string    `json:"product_title"`
	ProductDescription     string    `json:"product_description"`
	ProductPrimaryImageUrl string    `json:"product_primary_image_url"`
	VariantID              uuid.UUID `json:"variant_id"`
	Color                  string    `json:"color"`
	Size                   string    `json:"size"`
	BuyingMode             string    `json:"buying_mode"`
	UnitPrice              string    `json:"unit_price"`
	HasDiscount            bool      `json:"has_discount"`
	DiscountType           string    `json:"discount_type"`
	DiscountValue          string    `json:"discount_value"`
	RequiredQuantity       int32     `json:"required_quantity"`
	WeightGrams            int32     `json:"weight_grams"`
	CreatedAt              time.Time `json:"created_at"`
}

func (q *Queries) InsertCheckoutItem(ctx context.Context, arg InsertCheckoutItemParams) (InsertCheckoutItemRow, error) {
	row := q.db.QueryRowContext(ctx, insertCheckoutItem,
		arg.ID,
		arg.CheckoutSessionID,
		arg.UserID,
		arg.SellerID,
		arg.SellerStoreName,
		arg.CategoryID,
		arg.CategoryName,
		arg.ProductID,
		arg.ProductTitle,
		arg.ProductDescription,
		arg.ProductPrimaryImageUrl,
		arg.VariantID,
		arg.Color,
		arg.Size,
		arg.BuyingMode,
		arg.UnitPrice,
		arg.HasDiscount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.RequiredQuantity,
		arg.WeightGrams,
		arg.CreatedAt,
	)
	var i InsertCheckoutItemRow
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.UserID,
		&i.SellerID,
		&i.SellerStoreName,
		&i.CategoryID,
		&i.CategoryName,
		&i.ProductID,
		&i.ProductTitle,
		&i.ProductDescription,
		&i.ProductPrimaryImageUrl,
		&i.VariantID,
		&i.Color,
		&i.Size,
		&i.BuyingMode,
		&i.UnitPrice,
		&i.HasDiscount,
		&i.DiscountType,
		&i.DiscountValue,
		&i.RequiredQuantity,
		&i.WeightGrams,
		&i.CreatedAt,
	)
	return i, err
}
