// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id,
    userid,
    event_type,
    event_payload,
    dispatched_at,
    created_at
) VALUES (
    $1,  $2,  $3,  $4,
    $5,  $6
)
`

type InsertEventParams struct {
	ID           uuid.UUID       `json:"id"`
	Userid       uuid.UUID       `json:"userid"`
	EventType    string          `json:"event_type"`
	EventPayload json.RawMessage `json:"event_payload"`
	DispatchedAt sql.NullTime    `json:"dispatched_at"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Userid,
		arg.EventType,
		arg.EventPayload,
		arg.DispatchedAt,
		arg.CreatedAt,
	)
	return err
}
