// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type SystemCheckLog struct {
	ID        uuid.UUID      `json:"id"`
	TestLabel sql.NullString `json:"test_label"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID                      uuid.UUID      `json:"id"`
	GoogleID                string         `json:"google_id"`
	PrimaryEmail            string         `json:"primary_email"`
	DisplayName             sql.NullString `json:"display_name"`
	ProfileImageUrl         sql.NullString `json:"profile_image_url"`
	IsArchived              sql.NullBool   `json:"is_archived"`
	IsBanned                sql.NullBool   `json:"is_banned"`
	IsMuted                 sql.NullBool   `json:"is_muted"`
	CurrentMode             sql.NullString `json:"current_mode"`
	IsSellerProfileApproved sql.NullBool   `json:"is_seller_profile_approved"`
	IsSellerProfileCreated  sql.NullBool   `json:"is_seller_profile_created"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
}
