// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (
    id,
    order_id,

    customer_id,
    seller_id,

    category_id,
    category_name,

    product_id,
    product_title,
    product_description,
    product_primary_image_url,

    variant_id,
    color,
    size,

    buying_mode,
    unit_price,
    quantity,
    total_price,

    has_discount,
    discount_type,
    discount_value,

    weight_grams_per_unit,
    total_weight_grams,

    seller_store_name,
    created_at
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22,
    $23, $24
)
`

type InsertOrderItemParams struct {
	ID                     uuid.UUID      `json:"id"`
	OrderID                uuid.UUID      `json:"order_id"`
	CustomerID             uuid.UUID      `json:"customer_id"`
	SellerID               uuid.UUID      `json:"seller_id"`
	CategoryID             uuid.UUID      `json:"category_id"`
	CategoryName           string         `json:"category_name"`
	ProductID              uuid.UUID      `json:"product_id"`
	ProductTitle           string         `json:"product_title"`
	ProductDescription     string         `json:"product_description"`
	ProductPrimaryImageUrl string         `json:"product_primary_image_url"`
	VariantID              uuid.UUID      `json:"variant_id"`
	Color                  string         `json:"color"`
	Size                   string         `json:"size"`
	BuyingMode             string         `json:"buying_mode"`
	UnitPrice              string         `json:"unit_price"`
	Quantity               int32          `json:"quantity"`
	TotalPrice             string         `json:"total_price"`
	HasDiscount            bool           `json:"has_discount"`
	DiscountType           sql.NullString `json:"discount_type"`
	DiscountValue          sql.NullString `json:"discount_value"`
	WeightGramsPerUnit     int32          `json:"weight_grams_per_unit"`
	TotalWeightGrams       int32          `json:"total_weight_grams"`
	SellerStoreName        string         `json:"seller_store_name"`
	CreatedAt              time.Time      `json:"created_at"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, insertOrderItem,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.SellerID,
		arg.CategoryID,
		arg.CategoryName,
		arg.ProductID,
		arg.ProductTitle,
		arg.ProductDescription,
		arg.ProductPrimaryImageUrl,
		arg.VariantID,
		arg.Color,
		arg.Size,
		arg.BuyingMode,
		arg.UnitPrice,
		arg.Quantity,
		arg.TotalPrice,
		arg.HasDiscount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.WeightGramsPerUnit,
		arg.TotalWeightGrams,
		arg.SellerStoreName,
		arg.CreatedAt,
	)
	return err
}
