// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertOrderRow = `-- name: InsertOrderRow :one
INSERT INTO orders (
    id,
    user_id,
    checkout_session_id,
    order_code,

    subtotal,
    shipping_fee,
    total_amount,
    currency,

    payment_method,
    payment_status,
    latest_payment_id,

    status,

    platform_discount_type,
    platform_discount_value,
    platform_discount_amount_applied,
    is_platform_discount_applied,

    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12,
    $13, $14, $15, $16,
    $17, $18
)
RETURNING
    id,
    user_id,
    checkout_session_id,
    order_code,
    subtotal,
    shipping_fee,
    total_amount,
    currency,
    payment_method,
    payment_status,
    latest_payment_id,
    status,
    platform_discount_type,
    platform_discount_value,
    platform_discount_amount_applied,
    is_platform_discount_applied,
    created_at,
    updated_at
`

type InsertOrderRowParams struct {
	ID                            uuid.UUID      `json:"id"`
	UserID                        uuid.UUID      `json:"user_id"`
	CheckoutSessionID             uuid.UUID      `json:"checkout_session_id"`
	OrderCode                     string         `json:"order_code"`
	Subtotal                      string         `json:"subtotal"`
	ShippingFee                   sql.NullString `json:"shipping_fee"`
	TotalAmount                   string         `json:"total_amount"`
	Currency                      sql.NullString `json:"currency"`
	PaymentMethod                 string         `json:"payment_method"`
	PaymentStatus                 sql.NullString `json:"payment_status"`
	LatestPaymentID               uuid.NullUUID  `json:"latest_payment_id"`
	Status                        sql.NullString `json:"status"`
	PlatformDiscountType          sql.NullString `json:"platform_discount_type"`
	PlatformDiscountValue         sql.NullString `json:"platform_discount_value"`
	PlatformDiscountAmountApplied sql.NullString `json:"platform_discount_amount_applied"`
	IsPlatformDiscountApplied     bool           `json:"is_platform_discount_applied"`
	CreatedAt                     sql.NullTime   `json:"created_at"`
	UpdatedAt                     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) InsertOrderRow(ctx context.Context, arg InsertOrderRowParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, insertOrderRow,
		arg.ID,
		arg.UserID,
		arg.CheckoutSessionID,
		arg.OrderCode,
		arg.Subtotal,
		arg.ShippingFee,
		arg.TotalAmount,
		arg.Currency,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.LatestPaymentID,
		arg.Status,
		arg.PlatformDiscountType,
		arg.PlatformDiscountValue,
		arg.PlatformDiscountAmountApplied,
		arg.IsPlatformDiscountApplied,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.OrderCode,
		&i.Subtotal,
		&i.ShippingFee,
		&i.TotalAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.LatestPaymentID,
		&i.Status,
		&i.PlatformDiscountType,
		&i.PlatformDiscountValue,
		&i.PlatformDiscountAmountApplied,
		&i.IsPlatformDiscountApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
