// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: platform_promotions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getActivePlatformPromotions = `-- name: GetActivePlatformPromotions :many
SELECT
    id,
    title,
    description,
    discount_type,
    discount_value,
    min_cart_value,
    max_cart_value,
    max_discount_cap,
    start_time,
    end_time,
    priority
FROM platform_promotions
WHERE is_active = true
  AND is_archived = false
`

type GetActivePlatformPromotionsRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	DiscountType   string         `json:"discount_type"`
	DiscountValue  string         `json:"discount_value"`
	MinCartValue   sql.NullString `json:"min_cart_value"`
	MaxCartValue   sql.NullString `json:"max_cart_value"`
	MaxDiscountCap sql.NullString `json:"max_discount_cap"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Priority       int32          `json:"priority"`
}

func (q *Queries) GetActivePlatformPromotions(ctx context.Context) ([]GetActivePlatformPromotionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePlatformPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePlatformPromotionsRow
	for rows.Next() {
		var i GetActivePlatformPromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinCartValue,
			&i.MaxCartValue,
			&i.MaxDiscountCap,
			&i.StartTime,
			&i.EndTime,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
