// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_variant_snapshots.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getVariantSnapshot = `-- name: GetVariantSnapshot :one
SELECT
    id,

    -- Category info
    categoryid,
    iscategoryarchived,
    categoryname,

    -- Seller info
    sellerid,
    issellerapproved,
    issellerarchived,
    issellerbanned,
    sellerstorename,

    -- Product info
    productid,
    isproductapproved,
    isproductarchived,
    isproductbanned,
    producttitle,
    productdescription,
    productprimaryimageurl,

    -- Variant info
    variantid,
    isvariantarchived,
    isvariantinstock,
    stockamount,
    color,
    size,
    retailprice,

    -- Retail discount (optional)
    hasretaildiscount,
    retaildiscounttype,
    retaildiscount,

    -- Wholesale (optional)
    haswholesaleenabled,
    wholesaleprice,
    wholesaleminquantity,
    haswholesalediscount,
    wholesalediscounttype,
    wholesalediscount,

    -- Weight and timestamps
    weight_grams,
    createdat,
    updatedat

FROM product_variant_snapshots
WHERE sellerid = $1 AND productid = $2 AND variantid = $3
`

type GetVariantSnapshotParams struct {
	Sellerid  uuid.UUID `json:"sellerid"`
	Productid uuid.UUID `json:"productid"`
	Variantid uuid.UUID `json:"variantid"`
}

func (q *Queries) GetVariantSnapshot(ctx context.Context, arg GetVariantSnapshotParams) (ProductVariantSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getVariantSnapshot, arg.Sellerid, arg.Productid, arg.Variantid)
	var i ProductVariantSnapshot
	err := row.Scan(
		&i.ID,
		&i.Categoryid,
		&i.Iscategoryarchived,
		&i.Categoryname,
		&i.Sellerid,
		&i.Issellerapproved,
		&i.Issellerarchived,
		&i.Issellerbanned,
		&i.Sellerstorename,
		&i.Productid,
		&i.Isproductapproved,
		&i.Isproductarchived,
		&i.Isproductbanned,
		&i.Producttitle,
		&i.Productdescription,
		&i.Productprimaryimageurl,
		&i.Variantid,
		&i.Isvariantarchived,
		&i.Isvariantinstock,
		&i.Stockamount,
		&i.Color,
		&i.Size,
		&i.Retailprice,
		&i.Hasretaildiscount,
		&i.Retaildiscounttype,
		&i.Retaildiscount,
		&i.Haswholesaleenabled,
		&i.Wholesaleprice,
		&i.Wholesaleminquantity,
		&i.Haswholesalediscount,
		&i.Wholesalediscounttype,
		&i.Wholesalediscount,
		&i.WeightGrams,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
