// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProductByIDAndSellerID = `-- name: GetProductByIDAndSellerID :one
SELECT
    id,
    seller_id,
    category_id,
    title,
    description,
    is_approved,
    is_banned,
    is_archived,
    created_at,
    updated_at
FROM products
WHERE id = $1
  AND seller_id = $2
`

type GetProductByIDAndSellerIDParams struct {
	ID       uuid.UUID `json:"id"`
	SellerID uuid.UUID `json:"seller_id"`
}

func (q *Queries) GetProductByIDAndSellerID(ctx context.Context, arg GetProductByIDAndSellerIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByIDAndSellerID, arg.ID, arg.SellerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.IsApproved,
		&i.IsBanned,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
    id,
    seller_id,
    category_id,
    title,
    description,
    is_approved,
    is_banned,
    is_archived,
    created_at,
    updated_at
) VALUES (
    $1,  $2,  $3,  $4,  $5,
    $6,  $7,  $8,  $9,  $10
)
RETURNING id
`

type InsertProductParams struct {
	ID          uuid.UUID `json:"id"`
	SellerID    uuid.UUID `json:"seller_id"`
	CategoryID  uuid.UUID `json:"category_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	IsApproved  bool      `json:"is_approved"`
	IsBanned    bool      `json:"is_banned"`
	IsArchived  bool      `json:"is_archived"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.IsApproved,
		arg.IsBanned,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
