// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_reviews.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveProductReview = `-- name: ArchiveProductReview :exec
UPDATE product_reviews
SET
    is_archived = $2,
    updated_at = $3
WHERE id = $1
`

type ArchiveProductReviewParams struct {
	ID         uuid.UUID `json:"id"`
	IsArchived bool      `json:"is_archived"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) ArchiveProductReview(ctx context.Context, arg ArchiveProductReviewParams) error {
	_, err := q.db.ExecContext(ctx, archiveProductReview, arg.ID, arg.IsArchived, arg.UpdatedAt)
	return err
}

const getAllReviewsByProductID = `-- name: GetAllReviewsByProductID :many
SELECT
    id,
    product_id,
    reviewer_user_id,
    review_text,
    review_image_url,
    is_edited,
    created_at,
    updated_at
FROM product_reviews
WHERE product_id = $1
  AND is_archived = FALSE
  AND is_banned = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllReviewsByProductIDParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetAllReviewsByProductIDRow struct {
	ID             uuid.UUID      `json:"id"`
	ProductID      uuid.UUID      `json:"product_id"`
	ReviewerUserID uuid.UUID      `json:"reviewer_user_id"`
	ReviewText     string         `json:"review_text"`
	ReviewImageUrl sql.NullString `json:"review_image_url"`
	IsEdited       bool           `json:"is_edited"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) GetAllReviewsByProductID(ctx context.Context, arg GetAllReviewsByProductIDParams) ([]GetAllReviewsByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllReviewsByProductID, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReviewsByProductIDRow
	for rows.Next() {
		var i GetAllReviewsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ReviewerUserID,
			&i.ReviewText,
			&i.ReviewImageUrl,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductReviewByID = `-- name: GetProductReviewByID :one
SELECT
    id,
    product_id,
    reviewer_user_id,
    review_text,
    review_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
FROM product_reviews
WHERE id = $1
`

func (q *Queries) GetProductReviewByID(ctx context.Context, id uuid.UUID) (ProductReview, error) {
	row := q.db.QueryRowContext(ctx, getProductReviewByID, id)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ReviewerUserID,
		&i.ReviewText,
		&i.ReviewImageUrl,
		&i.IsEdited,
		&i.IsArchived,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductReviewByIDAndProductIDAndReviewerID = `-- name: GetProductReviewByIDAndProductIDAndReviewerID :one
SELECT
    id,
    product_id,
    reviewer_user_id,
    review_text,
    review_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
FROM product_reviews
WHERE id = $1 AND product_id = $2 AND reviewer_user_id = $3
`

type GetProductReviewByIDAndProductIDAndReviewerIDParams struct {
	ID             uuid.UUID `json:"id"`
	ProductID      uuid.UUID `json:"product_id"`
	ReviewerUserID uuid.UUID `json:"reviewer_user_id"`
}

func (q *Queries) GetProductReviewByIDAndProductIDAndReviewerID(ctx context.Context, arg GetProductReviewByIDAndProductIDAndReviewerIDParams) (ProductReview, error) {
	row := q.db.QueryRowContext(ctx, getProductReviewByIDAndProductIDAndReviewerID, arg.ID, arg.ProductID, arg.ReviewerUserID)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ReviewerUserID,
		&i.ReviewText,
		&i.ReviewImageUrl,
		&i.IsEdited,
		&i.IsArchived,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductReview = `-- name: InsertProductReview :one
INSERT INTO product_reviews (
    id,
    product_id,
    reviewer_user_id,
    review_text,
    review_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertProductReviewParams struct {
	ID             uuid.UUID      `json:"id"`
	ProductID      uuid.UUID      `json:"product_id"`
	ReviewerUserID uuid.UUID      `json:"reviewer_user_id"`
	ReviewText     string         `json:"review_text"`
	ReviewImageUrl sql.NullString `json:"review_image_url"`
	IsEdited       bool           `json:"is_edited"`
	IsArchived     bool           `json:"is_archived"`
	IsBanned       bool           `json:"is_banned"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) InsertProductReview(ctx context.Context, arg InsertProductReviewParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertProductReview,
		arg.ID,
		arg.ProductID,
		arg.ReviewerUserID,
		arg.ReviewText,
		arg.ReviewImageUrl,
		arg.IsEdited,
		arg.IsArchived,
		arg.IsBanned,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProductReviewText = `-- name: UpdateProductReviewText :exec
UPDATE product_reviews
SET
    review_text = $4,
    is_edited = $5,
    updated_at = $6
WHERE id = $1 AND product_id = $2 AND reviewer_user_id = $3
`

type UpdateProductReviewTextParams struct {
	ID             uuid.UUID `json:"id"`
	ProductID      uuid.UUID `json:"product_id"`
	ReviewerUserID uuid.UUID `json:"reviewer_user_id"`
	ReviewText     string    `json:"review_text"`
	IsEdited       bool      `json:"is_edited"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProductReviewText(ctx context.Context, arg UpdateProductReviewTextParams) error {
	_, err := q.db.ExecContext(ctx, updateProductReviewText,
		arg.ID,
		arg.ProductID,
		arg.ReviewerUserID,
		arg.ReviewText,
		arg.IsEdited,
		arg.UpdatedAt,
	)
	return err
}
