// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_variants.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveProductVariant = `-- name: ArchiveProductVariant :exec
UPDATE product_variants
SET is_archived = $3, updated_at = $4
WHERE id = $1 AND product_id = $2
`

type ArchiveProductVariantParams struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	IsArchived bool      `json:"is_archived"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) ArchiveProductVariant(ctx context.Context, arg ArchiveProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, archiveProductVariant,
		arg.ID,
		arg.ProductID,
		arg.IsArchived,
		arg.UpdatedAt,
	)
	return err
}

const disableRetailDiscount = `-- name: DisableRetailDiscount :exec
UPDATE product_variants
SET hasretaildiscount = $1,
    retaildiscounttype = $2,
    retaildiscount = $3,
    updated_at = $4
WHERE id = $5 AND product_id = $6
`

type DisableRetailDiscountParams struct {
	Hasretaildiscount  bool           `json:"hasretaildiscount"`
	Retaildiscounttype sql.NullString `json:"retaildiscounttype"`
	Retaildiscount     sql.NullInt64  `json:"retaildiscount"`
	UpdatedAt          time.Time      `json:"updated_at"`
	ID                 uuid.UUID      `json:"id"`
	ProductID          uuid.UUID      `json:"product_id"`
}

func (q *Queries) DisableRetailDiscount(ctx context.Context, arg DisableRetailDiscountParams) error {
	_, err := q.db.ExecContext(ctx, disableRetailDiscount,
		arg.Hasretaildiscount,
		arg.Retaildiscounttype,
		arg.Retaildiscount,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const disableWholesaleDiscount = `-- name: DisableWholesaleDiscount :exec
UPDATE product_variants
SET haswholesalediscount = $1,
    wholesalediscounttype = $2,
    wholesalediscount = $3,
    updated_at = $4
WHERE id = $5 AND product_id = $6
`

type DisableWholesaleDiscountParams struct {
	Haswholesalediscount  bool           `json:"haswholesalediscount"`
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ID                    uuid.UUID      `json:"id"`
	ProductID             uuid.UUID      `json:"product_id"`
}

func (q *Queries) DisableWholesaleDiscount(ctx context.Context, arg DisableWholesaleDiscountParams) error {
	_, err := q.db.ExecContext(ctx, disableWholesaleDiscount,
		arg.Haswholesalediscount,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const disableWholesaleMode = `-- name: DisableWholesaleMode :exec
UPDATE product_variants
SET wholesale_enabled = $1,
    wholesale_price = $2,
    min_qty_wholesale = $3,
    haswholesalediscount = $4,
    wholesalediscounttype = $5,
    wholesalediscount = $6,
    updated_at = $7
WHERE id = $8 AND product_id = $9
`

type DisableWholesaleModeParams struct {
	WholesaleEnabled      bool           `json:"wholesale_enabled"`
	WholesalePrice        sql.NullInt64  `json:"wholesale_price"`
	MinQtyWholesale       sql.NullInt32  `json:"min_qty_wholesale"`
	Haswholesalediscount  bool           `json:"haswholesalediscount"`
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ID                    uuid.UUID      `json:"id"`
	ProductID             uuid.UUID      `json:"product_id"`
}

func (q *Queries) DisableWholesaleMode(ctx context.Context, arg DisableWholesaleModeParams) error {
	_, err := q.db.ExecContext(ctx, disableWholesaleMode,
		arg.WholesaleEnabled,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.Haswholesalediscount,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const enableRetailDiscount = `-- name: EnableRetailDiscount :exec
UPDATE product_variants
SET hasretaildiscount = $1,
    retaildiscounttype = $2,
    retaildiscount = $3,
    updated_at = $4
WHERE id = $5 AND product_id = $6
`

type EnableRetailDiscountParams struct {
	Hasretaildiscount  bool           `json:"hasretaildiscount"`
	Retaildiscounttype sql.NullString `json:"retaildiscounttype"`
	Retaildiscount     sql.NullInt64  `json:"retaildiscount"`
	UpdatedAt          time.Time      `json:"updated_at"`
	ID                 uuid.UUID      `json:"id"`
	ProductID          uuid.UUID      `json:"product_id"`
}

func (q *Queries) EnableRetailDiscount(ctx context.Context, arg EnableRetailDiscountParams) error {
	_, err := q.db.ExecContext(ctx, enableRetailDiscount,
		arg.Hasretaildiscount,
		arg.Retaildiscounttype,
		arg.Retaildiscount,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const enableWholesaleDiscount = `-- name: EnableWholesaleDiscount :exec
UPDATE product_variants
SET haswholesalediscount = $6,
    wholesalediscounttype = $5,
    wholesalediscount = $4,
    updated_at = $3
WHERE id = $1 AND product_id = $2
`

type EnableWholesaleDiscountParams struct {
	ID                    uuid.UUID      `json:"id"`
	ProductID             uuid.UUID      `json:"product_id"`
	UpdatedAt             time.Time      `json:"updated_at"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Haswholesalediscount  bool           `json:"haswholesalediscount"`
}

func (q *Queries) EnableWholesaleDiscount(ctx context.Context, arg EnableWholesaleDiscountParams) error {
	_, err := q.db.ExecContext(ctx, enableWholesaleDiscount,
		arg.ID,
		arg.ProductID,
		arg.UpdatedAt,
		arg.Wholesalediscount,
		arg.Wholesalediscounttype,
		arg.Haswholesalediscount,
	)
	return err
}

const enableWholesaleMode = `-- name: EnableWholesaleMode :exec
UPDATE product_variants
SET wholesale_enabled = $1,
    wholesale_price = $2,
    min_qty_wholesale = $3,
    haswholesalediscount = $4,
    wholesalediscounttype = $5,
    wholesalediscount = $6,
    updated_at = $7
WHERE id = $8 AND product_id = $9
`

type EnableWholesaleModeParams struct {
	WholesaleEnabled      bool           `json:"wholesale_enabled"`
	WholesalePrice        sql.NullInt64  `json:"wholesale_price"`
	MinQtyWholesale       sql.NullInt32  `json:"min_qty_wholesale"`
	Haswholesalediscount  bool           `json:"haswholesalediscount"`
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ID                    uuid.UUID      `json:"id"`
	ProductID             uuid.UUID      `json:"product_id"`
}

func (q *Queries) EnableWholesaleMode(ctx context.Context, arg EnableWholesaleModeParams) error {
	_, err := q.db.ExecContext(ctx, enableWholesaleMode,
		arg.WholesaleEnabled,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.Haswholesalediscount,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const insertProductVariantReturningID = `-- name: InsertProductVariantReturningID :one
INSERT INTO product_variants (
    id,
    product_id,
    color,
    size,
    retail_price,
    retaildiscounttype,
    retaildiscount,
    wholesale_enabled,
    wholesale_price,
    min_qty_wholesale,
    wholesalediscounttype,
    wholesalediscount,
    stock_quantity,
    in_stock,
    weight_grams,
    is_archived,
    created_at,
    updated_at,
    hasretaildiscount,
    haswholesalediscount
) VALUES (
    $1,  $2,  $3,  $4,  $5,
    $6,  $7,  $8,  $9,  $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20
)
RETURNING id
`

type InsertProductVariantReturningIDParams struct {
	ID                    uuid.UUID      `json:"id"`
	ProductID             uuid.UUID      `json:"product_id"`
	Color                 string         `json:"color"`
	Size                  string         `json:"size"`
	RetailPrice           int64          `json:"retail_price"`
	Retaildiscounttype    sql.NullString `json:"retaildiscounttype"`
	Retaildiscount        sql.NullInt64  `json:"retaildiscount"`
	WholesaleEnabled      bool           `json:"wholesale_enabled"`
	WholesalePrice        sql.NullInt64  `json:"wholesale_price"`
	MinQtyWholesale       sql.NullInt32  `json:"min_qty_wholesale"`
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	StockQuantity         int32          `json:"stock_quantity"`
	InStock               bool           `json:"in_stock"`
	WeightGrams           int32          `json:"weight_grams"`
	IsArchived            bool           `json:"is_archived"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	Hasretaildiscount     bool           `json:"hasretaildiscount"`
	Haswholesalediscount  bool           `json:"haswholesalediscount"`
}

func (q *Queries) InsertProductVariantReturningID(ctx context.Context, arg InsertProductVariantReturningIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertProductVariantReturningID,
		arg.ID,
		arg.ProductID,
		arg.Color,
		arg.Size,
		arg.RetailPrice,
		arg.Retaildiscounttype,
		arg.Retaildiscount,
		arg.WholesaleEnabled,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.StockQuantity,
		arg.InStock,
		arg.WeightGrams,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Hasretaildiscount,
		arg.Haswholesalediscount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRetailDiscount = `-- name: UpdateRetailDiscount :exec
UPDATE product_variants
SET
    retaildiscounttype = COALESCE($1::TEXT, retaildiscounttype),
    retaildiscount     = COALESCE($2::BIGINT, retaildiscount),
    updated_at         = $3
WHERE id = $4
  AND product_id = $5
`

type UpdateRetailDiscountParams struct {
	Retaildiscounttype sql.NullString `json:"retaildiscounttype"`
	Retaildiscount     sql.NullInt64  `json:"retaildiscount"`
	UpdatedAt          time.Time      `json:"updated_at"`
	VariantID          uuid.UUID      `json:"variant_id"`
	ProductID          uuid.UUID      `json:"product_id"`
}

func (q *Queries) UpdateRetailDiscount(ctx context.Context, arg UpdateRetailDiscountParams) error {
	_, err := q.db.ExecContext(ctx, updateRetailDiscount,
		arg.Retaildiscounttype,
		arg.Retaildiscount,
		arg.UpdatedAt,
		arg.VariantID,
		arg.ProductID,
	)
	return err
}

const updateVariantColorSize = `-- name: UpdateVariantColorSize :exec
UPDATE product_variants
SET
    color = COALESCE($1::TEXT, color),
    size  = COALESCE($2::TEXT, size),
    updated_at = $3
WHERE id = $4
  AND product_id = $5
`

type UpdateVariantColorSizeParams struct {
	Color     sql.NullString `json:"color"`
	Size      sql.NullString `json:"size"`
	UpdatedAt time.Time      `json:"updated_at"`
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
}

func (q *Queries) UpdateVariantColorSize(ctx context.Context, arg UpdateVariantColorSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantColorSize,
		arg.Color,
		arg.Size,
		arg.UpdatedAt,
		arg.VariantID,
		arg.ProductID,
	)
	return err
}

const updateVariantInStock = `-- name: UpdateVariantInStock :exec
UPDATE product_variants
SET in_stock = $1, updated_at = $2
WHERE id = $3 AND product_id = $4
`

type UpdateVariantInStockParams struct {
	InStock   bool      `json:"in_stock"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) UpdateVariantInStock(ctx context.Context, arg UpdateVariantInStockParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantInStock,
		arg.InStock,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const updateVariantRetailPrice = `-- name: UpdateVariantRetailPrice :exec
UPDATE product_variants
SET retail_price = $1, updated_at = $2
WHERE id = $3 AND product_id = $4
`

type UpdateVariantRetailPriceParams struct {
	RetailPrice int64     `json:"retail_price"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          uuid.UUID `json:"id"`
	ProductID   uuid.UUID `json:"product_id"`
}

func (q *Queries) UpdateVariantRetailPrice(ctx context.Context, arg UpdateVariantRetailPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantRetailPrice,
		arg.RetailPrice,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const updateVariantStockQuantity = `-- name: UpdateVariantStockQuantity :exec
UPDATE product_variants
SET stock_quantity = $1, updated_at = $2
WHERE id = $3 AND product_id = $4
`

type UpdateVariantStockQuantityParams struct {
	StockQuantity int32     `json:"stock_quantity"`
	UpdatedAt     time.Time `json:"updated_at"`
	ID            uuid.UUID `json:"id"`
	ProductID     uuid.UUID `json:"product_id"`
}

func (q *Queries) UpdateVariantStockQuantity(ctx context.Context, arg UpdateVariantStockQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantStockQuantity,
		arg.StockQuantity,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const updateVariantWeight = `-- name: UpdateVariantWeight :exec
UPDATE product_variants
SET weight_grams = $1, updated_at = $2
WHERE id = $3 AND product_id = $4
`

type UpdateVariantWeightParams struct {
	WeightGrams int32     `json:"weight_grams"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          uuid.UUID `json:"id"`
	ProductID   uuid.UUID `json:"product_id"`
}

func (q *Queries) UpdateVariantWeight(ctx context.Context, arg UpdateVariantWeightParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantWeight,
		arg.WeightGrams,
		arg.UpdatedAt,
		arg.ID,
		arg.ProductID,
	)
	return err
}

const updateWholesaleDiscount = `-- name: UpdateWholesaleDiscount :exec
UPDATE product_variants
SET
    wholesalediscounttype = COALESCE($1::TEXT, wholesalediscounttype),
    wholesalediscount     = COALESCE($2::BIGINT, wholesalediscount),
    updated_at            = $3
WHERE id = $4
  AND product_id = $5
`

type UpdateWholesaleDiscountParams struct {
	Wholesalediscounttype sql.NullString `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64  `json:"wholesalediscount"`
	UpdatedAt             time.Time      `json:"updated_at"`
	VariantID             uuid.UUID      `json:"variant_id"`
	ProductID             uuid.UUID      `json:"product_id"`
}

func (q *Queries) UpdateWholesaleDiscount(ctx context.Context, arg UpdateWholesaleDiscountParams) error {
	_, err := q.db.ExecContext(ctx, updateWholesaleDiscount,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.UpdatedAt,
		arg.VariantID,
		arg.ProductID,
	)
	return err
}

const updateWholesaleMode = `-- name: UpdateWholesaleMode :exec
UPDATE product_variants
SET
    wholesale_price    = COALESCE($1::BIGINT, wholesale_price),
    min_qty_wholesale  = COALESCE($2::INT, min_qty_wholesale),
    updated_at         = $3
WHERE id = $4
  AND product_id = $5
`

type UpdateWholesaleModeParams struct {
	WholesalePrice  sql.NullInt64 `json:"wholesale_price"`
	MinQtyWholesale sql.NullInt32 `json:"min_qty_wholesale"`
	UpdatedAt       time.Time     `json:"updated_at"`
	VariantID       uuid.UUID     `json:"variant_id"`
	ProductID       uuid.UUID     `json:"product_id"`
}

func (q *Queries) UpdateWholesaleMode(ctx context.Context, arg UpdateWholesaleModeParams) error {
	_, err := q.db.ExecContext(ctx, updateWholesaleMode,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.UpdatedAt,
		arg.VariantID,
		arg.ProductID,
	)
	return err
}
