// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_review_replies.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const archiveReviewReply = `-- name: ArchiveReviewReply :exec
UPDATE product_review_replies
SET
    is_archived = $3,
    updated_at = $4
WHERE review_id = $1 AND seller_user_id = $2
`

type ArchiveReviewReplyParams struct {
	ReviewID     uuid.UUID `json:"review_id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
	IsArchived   bool      `json:"is_archived"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ArchiveReviewReply(ctx context.Context, arg ArchiveReviewReplyParams) error {
	_, err := q.db.ExecContext(ctx, archiveReviewReply,
		arg.ReviewID,
		arg.SellerUserID,
		arg.IsArchived,
		arg.UpdatedAt,
	)
	return err
}

const getRepliesByReviewIDs = `-- name: GetRepliesByReviewIDs :many
SELECT
    id,
    review_id,
    seller_user_id,
    reply_text,
    reply_image_url,
    is_edited,
    created_at,
    updated_at
FROM product_review_replies
WHERE review_id = ANY($1::uuid[])
  AND is_archived = FALSE
  AND is_banned = FALSE
`

type GetRepliesByReviewIDsRow struct {
	ID            uuid.UUID      `json:"id"`
	ReviewID      uuid.UUID      `json:"review_id"`
	SellerUserID  uuid.UUID      `json:"seller_user_id"`
	ReplyText     string         `json:"reply_text"`
	ReplyImageUrl sql.NullString `json:"reply_image_url"`
	IsEdited      bool           `json:"is_edited"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetRepliesByReviewIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetRepliesByReviewIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRepliesByReviewIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepliesByReviewIDsRow
	for rows.Next() {
		var i GetRepliesByReviewIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.SellerUserID,
			&i.ReplyText,
			&i.ReplyImageUrl,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewReplyByReviewID = `-- name: GetReviewReplyByReviewID :one
SELECT
    id,
    review_id,
    seller_user_id,
    reply_text,
    reply_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
FROM product_review_replies
WHERE review_id = $1
`

func (q *Queries) GetReviewReplyByReviewID(ctx context.Context, reviewID uuid.UUID) (ProductReviewReply, error) {
	row := q.db.QueryRowContext(ctx, getReviewReplyByReviewID, reviewID)
	var i ProductReviewReply
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.SellerUserID,
		&i.ReplyText,
		&i.ReplyImageUrl,
		&i.IsEdited,
		&i.IsArchived,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewReplyByReviewIDAndSellerID = `-- name: GetReviewReplyByReviewIDAndSellerID :one
SELECT
    id,
    review_id,
    seller_user_id,
    reply_text,
    reply_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
FROM product_review_replies
WHERE review_id = $1 AND seller_user_id = $2
`

type GetReviewReplyByReviewIDAndSellerIDParams struct {
	ReviewID     uuid.UUID `json:"review_id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
}

func (q *Queries) GetReviewReplyByReviewIDAndSellerID(ctx context.Context, arg GetReviewReplyByReviewIDAndSellerIDParams) (ProductReviewReply, error) {
	row := q.db.QueryRowContext(ctx, getReviewReplyByReviewIDAndSellerID, arg.ReviewID, arg.SellerUserID)
	var i ProductReviewReply
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.SellerUserID,
		&i.ReplyText,
		&i.ReplyImageUrl,
		&i.IsEdited,
		&i.IsArchived,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReviewReply = `-- name: InsertReviewReply :one
INSERT INTO product_review_replies (
    id,
    review_id,
    seller_user_id,
    reply_text,
    reply_image_url,
    is_edited,
    is_archived,
    is_banned,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertReviewReplyParams struct {
	ID            uuid.UUID      `json:"id"`
	ReviewID      uuid.UUID      `json:"review_id"`
	SellerUserID  uuid.UUID      `json:"seller_user_id"`
	ReplyText     string         `json:"reply_text"`
	ReplyImageUrl sql.NullString `json:"reply_image_url"`
	IsEdited      bool           `json:"is_edited"`
	IsArchived    bool           `json:"is_archived"`
	IsBanned      bool           `json:"is_banned"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) InsertReviewReply(ctx context.Context, arg InsertReviewReplyParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertReviewReply,
		arg.ID,
		arg.ReviewID,
		arg.SellerUserID,
		arg.ReplyText,
		arg.ReplyImageUrl,
		arg.IsEdited,
		arg.IsArchived,
		arg.IsBanned,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateReviewReplyText = `-- name: UpdateReviewReplyText :exec
UPDATE product_review_replies
SET
    reply_text = $3,
    is_edited = $4,
    updated_at = $5
WHERE review_id = $1 AND seller_user_id = $2
`

type UpdateReviewReplyTextParams struct {
	ReviewID     uuid.UUID `json:"review_id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
	ReplyText    string    `json:"reply_text"`
	IsEdited     bool      `json:"is_edited"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpdateReviewReplyText(ctx context.Context, arg UpdateReviewReplyTextParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewReplyText,
		arg.ReviewID,
		arg.SellerUserID,
		arg.ReplyText,
		arg.IsEdited,
		arg.UpdatedAt,
	)
	return err
}
