// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_medias.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProductMedia = `-- name: ArchiveProductMedia :exec
UPDATE product_medias
SET is_archived = $4
WHERE id = $1 AND product_id = $2 AND media_type = $3
`

type ArchiveProductMediaParams struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) ArchiveProductMedia(ctx context.Context, arg ArchiveProductMediaParams) error {
	_, err := q.db.ExecContext(ctx, archiveProductMedia,
		arg.ID,
		arg.ProductID,
		arg.MediaType,
		arg.IsArchived,
	)
	return err
}

const countActiveImagesForProduct = `-- name: CountActiveImagesForProduct :one
SELECT COUNT(*) FROM product_medias
WHERE product_id = $1 AND media_type = $2 AND is_archived = $3
`

type CountActiveImagesForProductParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) CountActiveImagesForProduct(ctx context.Context, arg CountActiveImagesForProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveImagesForProduct, arg.ProductID, arg.MediaType, arg.IsArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveMediasByProductID = `-- name: GetActiveMediasByProductID :many
SELECT
  id,
  product_id,
  media_type,
  media_url,
  is_primary,
  is_archived,
  created_at,
  updated_at
FROM product_medias
WHERE product_id = $1
  AND media_type = $2
  AND is_archived = $3
ORDER BY created_at ASC
`

type GetActiveMediasByProductIDParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) GetActiveMediasByProductID(ctx context.Context, arg GetActiveMediasByProductIDParams) ([]ProductMedia, error) {
	rows, err := q.db.QueryContext(ctx, getActiveMediasByProductID, arg.ProductID, arg.MediaType, arg.IsArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedia
	for rows.Next() {
		var i ProductMedia
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.MediaType,
			&i.MediaUrl,
			&i.IsPrimary,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryProductImageByProductID = `-- name: GetPrimaryProductImageByProductID :one
SELECT
    id,
    product_id,
    media_type,
    media_url,
    is_primary,
    is_archived,
    created_at,
    updated_at
FROM product_medias
WHERE product_id = $1
  AND media_type = $2
  AND is_primary = $3
  AND is_archived = $4
LIMIT 1
`

type GetPrimaryProductImageByProductIDParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsPrimary  bool      `json:"is_primary"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) GetPrimaryProductImageByProductID(ctx context.Context, arg GetPrimaryProductImageByProductIDParams) (ProductMedia, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryProductImageByProductID,
		arg.ProductID,
		arg.MediaType,
		arg.IsPrimary,
		arg.IsArchived,
	)
	var i ProductMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.MediaType,
		&i.MediaUrl,
		&i.IsPrimary,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductMediaByID = `-- name: GetProductMediaByID :one
SELECT
  id,
  product_id,
  media_type,
  media_url,
  is_primary,
  is_archived
FROM product_medias
WHERE id = $1 AND product_id = $2 AND media_type = $3
`

type GetProductMediaByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	MediaType string    `json:"media_type"`
}

type GetProductMediaByIDRow struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	MediaUrl   string    `json:"media_url"`
	IsPrimary  bool      `json:"is_primary"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) GetProductMediaByID(ctx context.Context, arg GetProductMediaByIDParams) (GetProductMediaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductMediaByID, arg.ID, arg.ProductID, arg.MediaType)
	var i GetProductMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.MediaType,
		&i.MediaUrl,
		&i.IsPrimary,
		&i.IsArchived,
	)
	return i, err
}

const getPromoVideoByProductID = `-- name: GetPromoVideoByProductID :one
SELECT id
FROM product_medias
WHERE product_id = $1
  AND media_type = $2
  AND is_archived = $3
LIMIT 1
`

type GetPromoVideoByProductIDParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsArchived bool      `json:"is_archived"`
}

func (q *Queries) GetPromoVideoByProductID(ctx context.Context, arg GetPromoVideoByProductIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPromoVideoByProductID, arg.ProductID, arg.MediaType, arg.IsArchived)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProductMedia = `-- name: InsertProductMedia :one
INSERT INTO product_medias (
  id,
  product_id,
  media_type,
  media_url,
  is_primary,
  is_archived,
  created_at,
  updated_at
)
VALUES (
  $1,  -- id (UUID)
  $2,  -- product_id (UUID)
  $3,  -- media_type (image or video)
  $4,  -- media_url
  $5,  -- is_primary
  $6,  -- is_archived
  $7,  -- created_at
  $8   -- updated_at
)
RETURNING id
`

type InsertProductMediaParams struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	MediaUrl   string    `json:"media_url"`
	IsPrimary  bool      `json:"is_primary"`
	IsArchived bool      `json:"is_archived"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) InsertProductMedia(ctx context.Context, arg InsertProductMediaParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertProductMedia,
		arg.ID,
		arg.ProductID,
		arg.MediaType,
		arg.MediaUrl,
		arg.IsPrimary,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setAsPrimaryImage = `-- name: SetAsPrimaryImage :exec
UPDATE product_medias
SET is_primary = $4
WHERE id = $1 AND product_id = $2 AND media_type = $3
`

type SetAsPrimaryImageParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	MediaType string    `json:"media_type"`
	IsPrimary bool      `json:"is_primary"`
}

func (q *Queries) SetAsPrimaryImage(ctx context.Context, arg SetAsPrimaryImageParams) error {
	_, err := q.db.ExecContext(ctx, setAsPrimaryImage,
		arg.ID,
		arg.ProductID,
		arg.MediaType,
		arg.IsPrimary,
	)
	return err
}

const unsetAllPrimaryImages = `-- name: UnsetAllPrimaryImages :exec
UPDATE product_medias
SET is_primary = $4
WHERE product_id = $1 AND media_type = $2 AND is_archived = $3
`

type UnsetAllPrimaryImagesParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	MediaType  string    `json:"media_type"`
	IsArchived bool      `json:"is_archived"`
	IsPrimary  bool      `json:"is_primary"`
}

func (q *Queries) UnsetAllPrimaryImages(ctx context.Context, arg UnsetAllPrimaryImagesParams) error {
	_, err := q.db.ExecContext(ctx, unsetAllPrimaryImages,
		arg.ProductID,
		arg.MediaType,
		arg.IsArchived,
		arg.IsPrimary,
	)
	return err
}
