// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_variant_indexes.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const applyRetailDiscountToIndex = `-- name: ApplyRetailDiscountToIndex :exec
UPDATE product_variant_indexes
SET
    has_retail_discount = $1,
    retaildiscount = $2,
    retaildiscounttype = $3,
    updatedat = $4
WHERE productid = $5
  AND variantid = $6
`

type ApplyRetailDiscountToIndexParams struct {
	HasRetailDiscount  bool           `json:"has_retail_discount"`
	RetailDiscount     sql.NullInt64  `json:"retail_discount"`
	RetailDiscountType sql.NullString `json:"retail_discount_type"`
	Updatedat          time.Time      `json:"updatedat"`
	Productid          uuid.UUID      `json:"productid"`
	Variantid          uuid.UUID      `json:"variantid"`
}

func (q *Queries) ApplyRetailDiscountToIndex(ctx context.Context, arg ApplyRetailDiscountToIndexParams) error {
	_, err := q.db.ExecContext(ctx, applyRetailDiscountToIndex,
		arg.HasRetailDiscount,
		arg.RetailDiscount,
		arg.RetailDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const applyWholesaleDiscountToIndex = `-- name: ApplyWholesaleDiscountToIndex :exec
UPDATE product_variant_indexes
SET
    wholesalediscount = $1,
    wholesalediscounttype = $2,
    updatedat = $3
WHERE productid = $4
  AND variantid = $5
`

type ApplyWholesaleDiscountToIndexParams struct {
	WholesaleDiscount     sql.NullInt64  `json:"wholesale_discount"`
	WholesaleDiscountType sql.NullString `json:"wholesale_discount_type"`
	Updatedat             time.Time      `json:"updatedat"`
	Productid             uuid.UUID      `json:"productid"`
	Variantid             uuid.UUID      `json:"variantid"`
}

func (q *Queries) ApplyWholesaleDiscountToIndex(ctx context.Context, arg ApplyWholesaleDiscountToIndexParams) error {
	_, err := q.db.ExecContext(ctx, applyWholesaleDiscountToIndex,
		arg.WholesaleDiscount,
		arg.WholesaleDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const archiveVariantInIndexes = `-- name: ArchiveVariantInIndexes :exec
UPDATE product_variant_indexes
SET
    isvariantarchived = $1,
    updatedat = $2
WHERE productid = $3
  AND variantid = $4
`

type ArchiveVariantInIndexesParams struct {
	Isvariantarchived bool      `json:"isvariantarchived"`
	Updatedat         time.Time `json:"updatedat"`
	Productid         uuid.UUID `json:"productid"`
	Variantid         uuid.UUID `json:"variantid"`
}

func (q *Queries) ArchiveVariantInIndexes(ctx context.Context, arg ArchiveVariantInIndexesParams) error {
	_, err := q.db.ExecContext(ctx, archiveVariantInIndexes,
		arg.Isvariantarchived,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const disableWholesaleModeInIndexes = `-- name: DisableWholesaleModeInIndexes :exec
UPDATE product_variant_indexes
SET
    haswholesaleenabled = $1,
    wholesaleprice = $2,
    wholesaleminquantity = $3,
    wholesalediscount = $4,
    wholesalediscounttype = $5,
    updatedat = $6
WHERE productid = $7
  AND variantid = $8
`

type DisableWholesaleModeInIndexesParams struct {
	HasWholesaleEnabled   bool           `json:"has_wholesale_enabled"`
	WholesalePrice        sql.NullInt64  `json:"wholesale_price"`
	WholesaleMinQuantity  sql.NullInt32  `json:"wholesale_min_quantity"`
	WholesaleDiscount     sql.NullInt64  `json:"wholesale_discount"`
	WholesaleDiscountType sql.NullString `json:"wholesale_discount_type"`
	Updatedat             time.Time      `json:"updatedat"`
	Productid             uuid.UUID      `json:"productid"`
	Variantid             uuid.UUID      `json:"variantid"`
}

func (q *Queries) DisableWholesaleModeInIndexes(ctx context.Context, arg DisableWholesaleModeInIndexesParams) error {
	_, err := q.db.ExecContext(ctx, disableWholesaleModeInIndexes,
		arg.HasWholesaleEnabled,
		arg.WholesalePrice,
		arg.WholesaleMinQuantity,
		arg.WholesaleDiscount,
		arg.WholesaleDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const enableWholesaleModeInIndexes = `-- name: EnableWholesaleModeInIndexes :exec
UPDATE product_variant_indexes
SET
    wholesaleprice = $1,
    wholesaleminquantity = $2,
    wholesalediscount = COALESCE($3::BIGINT, NULL),
    wholesalediscounttype = COALESCE($4::TEXT, NULL),
    haswholesaleenabled = $5,
    updatedat = $6
WHERE productid = $7
  AND variantid = $8
`

type EnableWholesaleModeInIndexesParams struct {
	WholesalePrice        sql.NullInt64  `json:"wholesale_price"`
	MinQtyWholesale       sql.NullInt32  `json:"min_qty_wholesale"`
	WholesaleDiscount     sql.NullInt64  `json:"wholesale_discount"`
	WholesaleDiscountType sql.NullString `json:"wholesale_discount_type"`
	HasWholesaleEnabled   bool           `json:"has_wholesale_enabled"`
	Updatedat             time.Time      `json:"updatedat"`
	Productid             uuid.UUID      `json:"productid"`
	Variantid             uuid.UUID      `json:"variantid"`
}

func (q *Queries) EnableWholesaleModeInIndexes(ctx context.Context, arg EnableWholesaleModeInIndexesParams) error {
	_, err := q.db.ExecContext(ctx, enableWholesaleModeInIndexes,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.WholesaleDiscount,
		arg.WholesaleDiscountType,
		arg.HasWholesaleEnabled,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const getAllProductVariantIndexesBySeller = `-- name: GetAllProductVariantIndexesBySeller :many
SELECT
  id,
  categoryid,
  iscategoryarchived,
  categoryname,
  sellerid,
  issellerapproved,
  issellerarchived,
  issellerbanned,
  sellerstorename,
  productid,
  isproductapproved,
  isproductarchived,
  isproductbanned,
  producttitle,
  productdescription,
  productimages,
  productpromovideourl,
  variantid,
  isvariantarchived,
  isvariantinstock,
  stockamount,
  color,
  size,
  retailprice,
  retaildiscounttype,
  retaildiscount,
  has_retail_discount,
  haswholesaleenabled,
  wholesaleprice,
  wholesaleminquantity,
  wholesalediscounttype,
  wholesalediscount,
  weight_grams,
  search_vector,
  views,
  createdat,
  updatedat
FROM product_variant_indexes
WHERE sellerid = $1
  AND issellerapproved = true
  AND issellerarchived = false
  AND issellerbanned = false
`

func (q *Queries) GetAllProductVariantIndexesBySeller(ctx context.Context, sellerid uuid.UUID) ([]ProductVariantIndex, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductVariantIndexesBySeller, sellerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariantIndex
	for rows.Next() {
		var i ProductVariantIndex
		if err := rows.Scan(
			&i.ID,
			&i.Categoryid,
			&i.Iscategoryarchived,
			&i.Categoryname,
			&i.Sellerid,
			&i.Issellerapproved,
			&i.Issellerarchived,
			&i.Issellerbanned,
			&i.Sellerstorename,
			&i.Productid,
			&i.Isproductapproved,
			&i.Isproductarchived,
			&i.Isproductbanned,
			&i.Producttitle,
			&i.Productdescription,
			pq.Array(&i.Productimages),
			&i.Productpromovideourl,
			&i.Variantid,
			&i.Isvariantarchived,
			&i.Isvariantinstock,
			&i.Stockamount,
			&i.Color,
			&i.Size,
			&i.Retailprice,
			&i.Retaildiscounttype,
			&i.Retaildiscount,
			&i.HasRetailDiscount,
			&i.Haswholesaleenabled,
			&i.Wholesaleprice,
			&i.Wholesaleminquantity,
			&i.Wholesalediscounttype,
			&i.Wholesalediscount,
			&i.WeightGrams,
			&i.SearchVector,
			&i.Views,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantIndexesByProductAndSeller = `-- name: GetVariantIndexesByProductAndSeller :many
SELECT
  id,
  categoryid,
  iscategoryarchived,
  categoryname,
  sellerid,
  issellerapproved,
  issellerarchived,
  issellerbanned,
  sellerstorename,
  productid,
  isproductapproved,
  isproductarchived,
  isproductbanned,
  producttitle,
  productdescription,
  productimages,
  productpromovideourl,
  variantid,
  isvariantarchived,
  isvariantinstock,
  stockamount,
  color,
  size,
  retailprice,
  retaildiscounttype,
  retaildiscount,
  has_retail_discount,
  haswholesaleenabled,
  wholesaleprice,
  wholesaleminquantity,
  wholesalediscounttype,
  wholesalediscount,
  weight_grams,
  search_vector,
  views,
  createdat,
  updatedat
FROM product_variant_indexes
WHERE productid = $1
  AND sellerid = $2
`

type GetVariantIndexesByProductAndSellerParams struct {
	Productid uuid.UUID `json:"productid"`
	Sellerid  uuid.UUID `json:"sellerid"`
}

func (q *Queries) GetVariantIndexesByProductAndSeller(ctx context.Context, arg GetVariantIndexesByProductAndSellerParams) ([]ProductVariantIndex, error) {
	rows, err := q.db.QueryContext(ctx, getVariantIndexesByProductAndSeller, arg.Productid, arg.Sellerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariantIndex
	for rows.Next() {
		var i ProductVariantIndex
		if err := rows.Scan(
			&i.ID,
			&i.Categoryid,
			&i.Iscategoryarchived,
			&i.Categoryname,
			&i.Sellerid,
			&i.Issellerapproved,
			&i.Issellerarchived,
			&i.Issellerbanned,
			&i.Sellerstorename,
			&i.Productid,
			&i.Isproductapproved,
			&i.Isproductarchived,
			&i.Isproductbanned,
			&i.Producttitle,
			&i.Productdescription,
			pq.Array(&i.Productimages),
			&i.Productpromovideourl,
			&i.Variantid,
			&i.Isvariantarchived,
			&i.Isvariantinstock,
			&i.Stockamount,
			&i.Color,
			&i.Size,
			&i.Retailprice,
			&i.Retaildiscounttype,
			&i.Retaildiscount,
			&i.HasRetailDiscount,
			&i.Haswholesaleenabled,
			&i.Wholesaleprice,
			&i.Wholesaleminquantity,
			&i.Wholesalediscounttype,
			&i.Wholesalediscount,
			&i.WeightGrams,
			&i.SearchVector,
			&i.Views,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProductVariantIndex = `-- name: InsertProductVariantIndex :exec
INSERT INTO product_variant_indexes (
    id,
    categoryid,
    iscategoryarchived,
    categoryname,

    sellerid,
    issellerapproved,
    issellerarchived,
    issellerbanned,
    sellerstorename,

    productid,
    isproductapproved,
    isproductarchived,
    isproductbanned,
    producttitle,
    productdescription,
    productimages,
    productpromovideourl,

    variantid,
    isvariantarchived,
    isvariantinstock,
    stockamount,
    color,
    size,
    retailprice,

    retaildiscounttype,
    retaildiscount,
    has_retail_discount,

    haswholesaleenabled,
    wholesaleprice,
    wholesaleminquantity,
    wholesalediscounttype,
    wholesalediscount,

    weight_grams,
    search_vector,
    views,
    createdat,
    updatedat
)
VALUES (
    $1,  -- id
    $2,  -- categoryid
    $3,  -- iscategoryarchived
    $4,  -- categoryname

    $5,  -- sellerid
    $6,  -- issellerapproved
    $7,  -- issellerarchived
    $8,  -- issellerbanned
    $9,  -- sellerstorename

    $10, -- productid
    $11, -- isproductapproved
    $12, -- isproductarchived
    $13, -- isproductbanned
    $14, -- producttitle
    $15, -- productdescription
    $16, -- productimages
    $17, -- productpromovideourl

    $18, -- variantid
    $19, -- isvariantarchived
    $20, -- isvariantinstock
    $21, -- stockamount
    $22, -- color
    $23, -- size
    $24, -- retailprice

    $25, -- retaildiscounttype
    $26, -- retaildiscount
    $27, -- has_retail_discount

    $28, -- haswholesaleenabled
    $29, -- wholesaleprice
    $30, -- wholesaleminquantity
    $31, -- wholesalediscounttype
    $32, -- wholesalediscount

    $33, -- weight_grams
    to_tsvector('english', $34), -- search_vector
    $35, -- views
    $36, -- createdat
    $37  -- updatedat
)
`

type InsertProductVariantIndexParams struct {
	ID                    uuid.UUID       `json:"id"`
	Categoryid            uuid.UUID       `json:"categoryid"`
	Iscategoryarchived    bool            `json:"iscategoryarchived"`
	Categoryname          string          `json:"categoryname"`
	Sellerid              uuid.UUID       `json:"sellerid"`
	Issellerapproved      bool            `json:"issellerapproved"`
	Issellerarchived      bool            `json:"issellerarchived"`
	Issellerbanned        bool            `json:"issellerbanned"`
	Sellerstorename       string          `json:"sellerstorename"`
	Productid             uuid.UUID       `json:"productid"`
	Isproductapproved     bool            `json:"isproductapproved"`
	Isproductarchived     bool            `json:"isproductarchived"`
	Isproductbanned       bool            `json:"isproductbanned"`
	Producttitle          string          `json:"producttitle"`
	Productdescription    string          `json:"productdescription"`
	Productimages         []string        `json:"productimages"`
	Productpromovideourl  sql.NullString  `json:"productpromovideourl"`
	Variantid             uuid.UUID       `json:"variantid"`
	Isvariantarchived     bool            `json:"isvariantarchived"`
	Isvariantinstock      bool            `json:"isvariantinstock"`
	Stockamount           int32           `json:"stockamount"`
	Color                 string          `json:"color"`
	Size                  string          `json:"size"`
	Retailprice           int64           `json:"retailprice"`
	Retaildiscounttype    sql.NullString  `json:"retaildiscounttype"`
	Retaildiscount        sql.NullInt64   `json:"retaildiscount"`
	HasRetailDiscount     bool            `json:"has_retail_discount"`
	Haswholesaleenabled   bool            `json:"haswholesaleenabled"`
	Wholesaleprice        sql.NullInt64   `json:"wholesaleprice"`
	Wholesaleminquantity  sql.NullInt32   `json:"wholesaleminquantity"`
	Wholesalediscounttype sql.NullString  `json:"wholesalediscounttype"`
	Wholesalediscount     sql.NullInt64   `json:"wholesalediscount"`
	WeightGrams           int32           `json:"weight_grams"`
	ToTsvector            json.RawMessage `json:"to_tsvector"`
	Views                 int64           `json:"views"`
	Createdat             time.Time       `json:"createdat"`
	Updatedat             time.Time       `json:"updatedat"`
}

func (q *Queries) InsertProductVariantIndex(ctx context.Context, arg InsertProductVariantIndexParams) error {
	_, err := q.db.ExecContext(ctx, insertProductVariantIndex,
		arg.ID,
		arg.Categoryid,
		arg.Iscategoryarchived,
		arg.Categoryname,
		arg.Sellerid,
		arg.Issellerapproved,
		arg.Issellerarchived,
		arg.Issellerbanned,
		arg.Sellerstorename,
		arg.Productid,
		arg.Isproductapproved,
		arg.Isproductarchived,
		arg.Isproductbanned,
		arg.Producttitle,
		arg.Productdescription,
		pq.Array(arg.Productimages),
		arg.Productpromovideourl,
		arg.Variantid,
		arg.Isvariantarchived,
		arg.Isvariantinstock,
		arg.Stockamount,
		arg.Color,
		arg.Size,
		arg.Retailprice,
		arg.Retaildiscounttype,
		arg.Retaildiscount,
		arg.HasRetailDiscount,
		arg.Haswholesaleenabled,
		arg.Wholesaleprice,
		arg.Wholesaleminquantity,
		arg.Wholesalediscounttype,
		arg.Wholesalediscount,
		arg.WeightGrams,
		arg.ToTsvector,
		arg.Views,
		arg.Createdat,
		arg.Updatedat,
	)
	return err
}

const markProductArchivedInProductVariantIndexes = `-- name: MarkProductArchivedInProductVariantIndexes :exec
UPDATE product_variant_indexes
SET
    isproductarchived = true,
    updatedat = $1
WHERE productid = $2
`

type MarkProductArchivedInProductVariantIndexesParams struct {
	Updatedat time.Time `json:"updatedat"`
	Productid uuid.UUID `json:"productid"`
}

func (q *Queries) MarkProductArchivedInProductVariantIndexes(ctx context.Context, arg MarkProductArchivedInProductVariantIndexesParams) error {
	_, err := q.db.ExecContext(ctx, markProductArchivedInProductVariantIndexes, arg.Updatedat, arg.Productid)
	return err
}

const removeRetailDiscountFromIndex = `-- name: RemoveRetailDiscountFromIndex :exec
UPDATE product_variant_indexes
SET
    has_retail_discount = $1,
    retaildiscount = $2,
    retaildiscounttype = $3,
    updatedat = $4
WHERE productid = $5
  AND variantid = $6
`

type RemoveRetailDiscountFromIndexParams struct {
	HasRetailDiscount  bool           `json:"has_retail_discount"`
	RetailDiscount     sql.NullInt64  `json:"retail_discount"`
	RetailDiscountType sql.NullString `json:"retail_discount_type"`
	Updatedat          time.Time      `json:"updatedat"`
	Productid          uuid.UUID      `json:"productid"`
	Variantid          uuid.UUID      `json:"variantid"`
}

func (q *Queries) RemoveRetailDiscountFromIndex(ctx context.Context, arg RemoveRetailDiscountFromIndexParams) error {
	_, err := q.db.ExecContext(ctx, removeRetailDiscountFromIndex,
		arg.HasRetailDiscount,
		arg.RetailDiscount,
		arg.RetailDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const removeWholesaleDiscountFromIndex = `-- name: RemoveWholesaleDiscountFromIndex :exec
UPDATE product_variant_indexes
SET
    wholesalediscount = $1,
    wholesalediscounttype = $2,
    updatedat = $3
WHERE productid = $4
  AND variantid = $5
`

type RemoveWholesaleDiscountFromIndexParams struct {
	WholesaleDiscount     sql.NullInt64  `json:"wholesale_discount"`
	WholesaleDiscountType sql.NullString `json:"wholesale_discount_type"`
	Updatedat             time.Time      `json:"updatedat"`
	Productid             uuid.UUID      `json:"productid"`
	Variantid             uuid.UUID      `json:"variantid"`
}

func (q *Queries) RemoveWholesaleDiscountFromIndex(ctx context.Context, arg RemoveWholesaleDiscountFromIndexParams) error {
	_, err := q.db.ExecContext(ctx, removeWholesaleDiscountFromIndex,
		arg.WholesaleDiscount,
		arg.WholesaleDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateCategoryInProductVariantIndexes = `-- name: UpdateCategoryInProductVariantIndexes :exec
UPDATE product_variant_indexes
SET
    categoryid = $1,
    categoryname = $2,
    updatedat = $3
WHERE productid = $4
`

type UpdateCategoryInProductVariantIndexesParams struct {
	Categoryid   uuid.UUID `json:"categoryid"`
	Categoryname string    `json:"categoryname"`
	Updatedat    time.Time `json:"updatedat"`
	Productid    uuid.UUID `json:"productid"`
}

func (q *Queries) UpdateCategoryInProductVariantIndexes(ctx context.Context, arg UpdateCategoryInProductVariantIndexesParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryInProductVariantIndexes,
		arg.Categoryid,
		arg.Categoryname,
		arg.Updatedat,
		arg.Productid,
	)
	return err
}

const updateIndexOnImageRemoved = `-- name: UpdateIndexOnImageRemoved :exec
UPDATE product_variant_indexes
SET
    productimages = array_remove(productimages, $1),
    updatedat = $2
WHERE productid = $3
`

type UpdateIndexOnImageRemovedParams struct {
	MediaUrl  interface{} `json:"media_url"`
	Updatedat time.Time   `json:"updatedat"`
	Productid uuid.UUID   `json:"productid"`
}

func (q *Queries) UpdateIndexOnImageRemoved(ctx context.Context, arg UpdateIndexOnImageRemovedParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnImageRemoved, arg.MediaUrl, arg.Updatedat, arg.Productid)
	return err
}

const updateIndexOnInStockUpdate = `-- name: UpdateIndexOnInStockUpdate :exec
UPDATE product_variant_indexes
SET
    isvariantinstock = $1,
    updatedat = $2
WHERE productid = $3
  AND variantid = $4
`

type UpdateIndexOnInStockUpdateParams struct {
	InStock   bool      `json:"in_stock"`
	Updatedat time.Time `json:"updatedat"`
	Productid uuid.UUID `json:"productid"`
	Variantid uuid.UUID `json:"variantid"`
}

func (q *Queries) UpdateIndexOnInStockUpdate(ctx context.Context, arg UpdateIndexOnInStockUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnInStockUpdate,
		arg.InStock,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateIndexOnProductImageAdded = `-- name: UpdateIndexOnProductImageAdded :exec
UPDATE product_variant_indexes
SET
    productimages = array_append(productimages, $1),
    updatedat = $2
WHERE productid = $3
`

type UpdateIndexOnProductImageAddedParams struct {
	MediaUrl  interface{} `json:"media_url"`
	Updatedat time.Time   `json:"updatedat"`
	Productid uuid.UUID   `json:"productid"`
}

func (q *Queries) UpdateIndexOnProductImageAdded(ctx context.Context, arg UpdateIndexOnProductImageAddedParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnProductImageAdded, arg.MediaUrl, arg.Updatedat, arg.Productid)
	return err
}

const updateIndexOnPromoVideoAdded = `-- name: UpdateIndexOnPromoVideoAdded :exec
UPDATE product_variant_indexes
SET
    productpromovideourl = $1,
    updatedat = $2
WHERE productid = $3
`

type UpdateIndexOnPromoVideoAddedParams struct {
	MediaUrl  sql.NullString `json:"media_url"`
	Updatedat time.Time      `json:"updatedat"`
	Productid uuid.UUID      `json:"productid"`
}

func (q *Queries) UpdateIndexOnPromoVideoAdded(ctx context.Context, arg UpdateIndexOnPromoVideoAddedParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnPromoVideoAdded, arg.MediaUrl, arg.Updatedat, arg.Productid)
	return err
}

const updateIndexOnPromoVideoRemoved = `-- name: UpdateIndexOnPromoVideoRemoved :exec
UPDATE product_variant_indexes
SET
    productpromovideourl = $1,
    updatedat = $2
WHERE productid = $3
`

type UpdateIndexOnPromoVideoRemovedParams struct {
	Productpromovideourl sql.NullString `json:"productpromovideourl"`
	Updatedat            time.Time      `json:"updatedat"`
	Productid            uuid.UUID      `json:"productid"`
}

func (q *Queries) UpdateIndexOnPromoVideoRemoved(ctx context.Context, arg UpdateIndexOnPromoVideoRemovedParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnPromoVideoRemoved, arg.Productpromovideourl, arg.Updatedat, arg.Productid)
	return err
}

const updateIndexOnRetailPriceUpdate = `-- name: UpdateIndexOnRetailPriceUpdate :exec
UPDATE product_variant_indexes
SET
    retailprice = $1,
    updatedat = $2
WHERE productid = $3
  AND variantid = $4
`

type UpdateIndexOnRetailPriceUpdateParams struct {
	RetailPrice int64     `json:"retail_price"`
	Updatedat   time.Time `json:"updatedat"`
	Productid   uuid.UUID `json:"productid"`
	Variantid   uuid.UUID `json:"variantid"`
}

func (q *Queries) UpdateIndexOnRetailPriceUpdate(ctx context.Context, arg UpdateIndexOnRetailPriceUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnRetailPriceUpdate,
		arg.RetailPrice,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateIndexOnStockQuantityUpdate = `-- name: UpdateIndexOnStockQuantityUpdate :exec
UPDATE product_variant_indexes
SET
    stockamount = $1,
    updatedat = $2
WHERE productid = $3
  AND variantid = $4
`

type UpdateIndexOnStockQuantityUpdateParams struct {
	StockQuantity int32     `json:"stock_quantity"`
	Updatedat     time.Time `json:"updatedat"`
	Productid     uuid.UUID `json:"productid"`
	Variantid     uuid.UUID `json:"variantid"`
}

func (q *Queries) UpdateIndexOnStockQuantityUpdate(ctx context.Context, arg UpdateIndexOnStockQuantityUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnStockQuantityUpdate,
		arg.StockQuantity,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateIndexOnVariantInfoUpdate = `-- name: UpdateIndexOnVariantInfoUpdate :exec
UPDATE product_variant_indexes
SET
    color = COALESCE($1::TEXT, color),
    size = COALESCE($2::TEXT, size),
    updatedat = $3
WHERE variantid = $4
  AND productid = $5
`

type UpdateIndexOnVariantInfoUpdateParams struct {
	Color     sql.NullString `json:"color"`
	Size      sql.NullString `json:"size"`
	Updatedat time.Time      `json:"updatedat"`
	Variantid uuid.UUID      `json:"variantid"`
	Productid uuid.UUID      `json:"productid"`
}

func (q *Queries) UpdateIndexOnVariantInfoUpdate(ctx context.Context, arg UpdateIndexOnVariantInfoUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnVariantInfoUpdate,
		arg.Color,
		arg.Size,
		arg.Updatedat,
		arg.Variantid,
		arg.Productid,
	)
	return err
}

const updateIndexOnWeightUpdate = `-- name: UpdateIndexOnWeightUpdate :exec
UPDATE product_variant_indexes
SET
    weight_grams = $1,
    updatedat = $2
WHERE productid = $3
  AND variantid = $4
`

type UpdateIndexOnWeightUpdateParams struct {
	WeightGrams int32     `json:"weight_grams"`
	Updatedat   time.Time `json:"updatedat"`
	Productid   uuid.UUID `json:"productid"`
	Variantid   uuid.UUID `json:"variantid"`
}

func (q *Queries) UpdateIndexOnWeightUpdate(ctx context.Context, arg UpdateIndexOnWeightUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexOnWeightUpdate,
		arg.WeightGrams,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateIndexesOnProductInfoUpdate = `-- name: UpdateIndexesOnProductInfoUpdate :exec
UPDATE product_variant_indexes
SET
    producttitle = COALESCE($1::TEXT, producttitle),
    productdescription = COALESCE($2::TEXT, productdescription),
    search_vector = to_tsvector('english', COALESCE($1::TEXT, producttitle) || ' ' || COALESCE($2::TEXT, productdescription)),
    updatedat = $3
WHERE productid = $4
`

type UpdateIndexesOnProductInfoUpdateParams struct {
	Producttitle       sql.NullString `json:"producttitle"`
	Productdescription sql.NullString `json:"productdescription"`
	Updatedat          time.Time      `json:"updatedat"`
	Productid          uuid.UUID      `json:"productid"`
}

func (q *Queries) UpdateIndexesOnProductInfoUpdate(ctx context.Context, arg UpdateIndexesOnProductInfoUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexesOnProductInfoUpdate,
		arg.Producttitle,
		arg.Productdescription,
		arg.Updatedat,
		arg.Productid,
	)
	return err
}

const updateRetailDiscountInIndex = `-- name: UpdateRetailDiscountInIndex :exec
UPDATE product_variant_indexes
SET
    retaildiscount = COALESCE($1::BIGINT, retaildiscount),
    retaildiscounttype = COALESCE($2::TEXT, retaildiscounttype),
    updatedat = $3
WHERE productid = $4
  AND variantid = $5
`

type UpdateRetailDiscountInIndexParams struct {
	RetailDiscount     sql.NullInt64  `json:"retail_discount"`
	RetailDiscountType sql.NullString `json:"retail_discount_type"`
	Updatedat          time.Time      `json:"updatedat"`
	Productid          uuid.UUID      `json:"productid"`
	Variantid          uuid.UUID      `json:"variantid"`
}

func (q *Queries) UpdateRetailDiscountInIndex(ctx context.Context, arg UpdateRetailDiscountInIndexParams) error {
	_, err := q.db.ExecContext(ctx, updateRetailDiscountInIndex,
		arg.RetailDiscount,
		arg.RetailDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateWholesaleDiscountInIndex = `-- name: UpdateWholesaleDiscountInIndex :exec
UPDATE product_variant_indexes
SET
    wholesalediscount = COALESCE($1::BIGINT, wholesalediscount),
    wholesalediscounttype = COALESCE($2::TEXT, wholesalediscounttype),
    updatedat = $3
WHERE productid = $4
  AND variantid = $5
`

type UpdateWholesaleDiscountInIndexParams struct {
	WholesaleDiscount     sql.NullInt64  `json:"wholesale_discount"`
	WholesaleDiscountType sql.NullString `json:"wholesale_discount_type"`
	Updatedat             time.Time      `json:"updatedat"`
	Productid             uuid.UUID      `json:"productid"`
	Variantid             uuid.UUID      `json:"variantid"`
}

func (q *Queries) UpdateWholesaleDiscountInIndex(ctx context.Context, arg UpdateWholesaleDiscountInIndexParams) error {
	_, err := q.db.ExecContext(ctx, updateWholesaleDiscountInIndex,
		arg.WholesaleDiscount,
		arg.WholesaleDiscountType,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}

const updateWholesaleModeInIndexes = `-- name: UpdateWholesaleModeInIndexes :exec
UPDATE product_variant_indexes
SET
    wholesaleprice = COALESCE($1::BIGINT, wholesaleprice),
    wholesaleminquantity = COALESCE($2::INT, wholesaleminquantity),
    updatedat = $3
WHERE productid = $4
  AND variantid = $5
`

type UpdateWholesaleModeInIndexesParams struct {
	WholesalePrice  sql.NullInt64 `json:"wholesale_price"`
	MinQtyWholesale sql.NullInt32 `json:"min_qty_wholesale"`
	Updatedat       time.Time     `json:"updatedat"`
	Productid       uuid.UUID     `json:"productid"`
	Variantid       uuid.UUID     `json:"variantid"`
}

func (q *Queries) UpdateWholesaleModeInIndexes(ctx context.Context, arg UpdateWholesaleModeInIndexesParams) error {
	_, err := q.db.ExecContext(ctx, updateWholesaleModeInIndexes,
		arg.WholesalePrice,
		arg.MinQtyWholesale,
		arg.Updatedat,
		arg.Productid,
		arg.Variantid,
	)
	return err
}
