// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seller_profile_metadata.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getSellerProfileMetadataBySellerID = `-- name: GetSellerProfileMetadataBySellerID :one
SELECT
    id,
    seller_id,

    sellerstorename,
    sellercontactno,
    sellerwhatsappcontactno,

    sellerwebsitelink,
    sellerfacebookpagename,
    selleremail,

    sellerphysicallocation,

    created_at,
    updated_at
FROM seller_profile_metadata
WHERE seller_id = $1
`

func (q *Queries) GetSellerProfileMetadataBySellerID(ctx context.Context, sellerID uuid.UUID) (SellerProfileMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getSellerProfileMetadataBySellerID, sellerID)
	var i SellerProfileMetadatum
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Sellerstorename,
		&i.Sellercontactno,
		&i.Sellerwhatsappcontactno,
		&i.Sellerwebsitelink,
		&i.Sellerfacebookpagename,
		&i.Selleremail,
		&i.Sellerphysicallocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSellerProfileMetadata = `-- name: InsertSellerProfileMetadata :one
INSERT INTO seller_profile_metadata (
  seller_id,
  sellerstorename,
  sellercontactno,
  sellerwhatsappcontactno,
  sellerwebsitelink,
  sellerfacebookpagename,
  selleremail,
  sellerphysicallocation,
  created_at,
  updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertSellerProfileMetadataParams struct {
	SellerID                uuid.UUID      `json:"seller_id"`
	Sellerstorename         string         `json:"sellerstorename"`
	Sellercontactno         string         `json:"sellercontactno"`
	Sellerwhatsappcontactno string         `json:"sellerwhatsappcontactno"`
	Sellerwebsitelink       sql.NullString `json:"sellerwebsitelink"`
	Sellerfacebookpagename  sql.NullString `json:"sellerfacebookpagename"`
	Selleremail             sql.NullString `json:"selleremail"`
	Sellerphysicallocation  string         `json:"sellerphysicallocation"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

func (q *Queries) InsertSellerProfileMetadata(ctx context.Context, arg InsertSellerProfileMetadataParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertSellerProfileMetadata,
		arg.SellerID,
		arg.Sellerstorename,
		arg.Sellercontactno,
		arg.Sellerwhatsappcontactno,
		arg.Sellerwebsitelink,
		arg.Sellerfacebookpagename,
		arg.Selleremail,
		arg.Sellerphysicallocation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
