// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shipping_addresses.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getShippingAddressByIDAndCheckoutID = `-- name: GetShippingAddressByIDAndCheckoutID :one
SELECT
    id,
    checkout_session_id,
    recipient_name,
    recipient_phone,
    recipient_email,
    address_line,
    delivery_note,
    city_id,
    zone_id,
    area_id,
    latitude,
    longitude,
    created_at
FROM shipping_addresses
WHERE id = $1
  AND checkout_session_id = $2
`

type GetShippingAddressByIDAndCheckoutIDParams struct {
	ID                uuid.UUID `json:"id"`
	CheckoutSessionID uuid.UUID `json:"checkout_session_id"`
}

func (q *Queries) GetShippingAddressByIDAndCheckoutID(ctx context.Context, arg GetShippingAddressByIDAndCheckoutIDParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, getShippingAddressByIDAndCheckoutID, arg.ID, arg.CheckoutSessionID)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientEmail,
		&i.AddressLine,
		&i.DeliveryNote,
		&i.CityID,
		&i.ZoneID,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const insertShippingAddress = `-- name: InsertShippingAddress :one
INSERT INTO shipping_addresses (
    id,
    checkout_session_id,
    recipient_name,
    recipient_phone,
    recipient_email,
    address_line,
    delivery_note,
    city_id,
    zone_id,
    area_id,
    latitude,
    longitude,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id
`

type InsertShippingAddressParams struct {
	ID                uuid.UUID      `json:"id"`
	CheckoutSessionID uuid.UUID      `json:"checkout_session_id"`
	RecipientName     string         `json:"recipient_name"`
	RecipientPhone    string         `json:"recipient_phone"`
	RecipientEmail    sql.NullString `json:"recipient_email"`
	AddressLine       string         `json:"address_line"`
	DeliveryNote      sql.NullString `json:"delivery_note"`
	CityID            int32          `json:"city_id"`
	ZoneID            int32          `json:"zone_id"`
	AreaID            int32          `json:"area_id"`
	Latitude          sql.NullString `json:"latitude"`
	Longitude         sql.NullString `json:"longitude"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

func (q *Queries) InsertShippingAddress(ctx context.Context, arg InsertShippingAddressParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertShippingAddress,
		arg.ID,
		arg.CheckoutSessionID,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.RecipientEmail,
		arg.AddressLine,
		arg.DeliveryNote,
		arg.CityID,
		arg.ZoneID,
		arg.AreaID,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateShippingAddressByID = `-- name: UpdateShippingAddressByID :exec
UPDATE shipping_addresses
SET
    recipient_name   = COALESCE($1, recipient_name),
    recipient_phone  = COALESCE($2, recipient_phone),
    recipient_email  = COALESCE($3, recipient_email),
    address_line     = COALESCE($4, address_line),
    delivery_note    = COALESCE($5, delivery_note),
    city_id          = COALESCE($6, city_id),
    zone_id          = COALESCE($7, zone_id),
    area_id          = COALESCE($8, area_id),
    latitude         = COALESCE($9, latitude),
    longitude        = COALESCE($10, longitude)
WHERE id = $11
`

type UpdateShippingAddressByIDParams struct {
	RecipientName  sql.NullString `json:"recipient_name"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
	RecipientEmail sql.NullString `json:"recipient_email"`
	AddressLine    sql.NullString `json:"address_line"`
	DeliveryNote   sql.NullString `json:"delivery_note"`
	CityID         sql.NullInt32  `json:"city_id"`
	ZoneID         sql.NullInt32  `json:"zone_id"`
	AreaID         sql.NullInt32  `json:"area_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateShippingAddressByID(ctx context.Context, arg UpdateShippingAddressByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateShippingAddressByID,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.RecipientEmail,
		arg.AddressLine,
		arg.DeliveryNote,
		arg.CityID,
		arg.ZoneID,
		arg.AreaID,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	return err
}
