// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system_check_log.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertSystemCheckLog = `-- name: InsertSystemCheckLog :one
INSERT INTO system_check_log (test_label)
VALUES ($1)
RETURNING id, created_at
`

type InsertSystemCheckLogRow struct {
	ID        uuid.UUID    `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) InsertSystemCheckLog(ctx context.Context, testLabel sql.NullString) (InsertSystemCheckLogRow, error) {
	row := q.db.QueryRowContext(ctx, insertSystemCheckLog, testLabel)
	var i InsertSystemCheckLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
