// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSessionByIDAndUserID = `-- name: GetSessionByIDAndUserID :one
SELECT
  id,
  user_id,
  ip_address,
  user_agent,
  device_fingerprint,
  is_revoked,
  is_archived,
  created_at,
  updated_at
FROM user_sessions
WHERE id = $1
  AND user_id = $2
`

type GetSessionByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSessionByIDAndUserID(ctx context.Context, arg GetSessionByIDAndUserIDParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByIDAndUserID, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.IsRevoked,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :one
INSERT INTO user_sessions (
  id, user_id, ip_address, user_agent, device_fingerprint,
  is_revoked, is_archived, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING id
`

type InsertUserSessionParams struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	IpAddress         string    `json:"ip_address"`
	UserAgent         string    `json:"user_agent"`
	DeviceFingerprint string    `json:"device_fingerprint"`
	IsRevoked         bool      `json:"is_revoked"`
	IsArchived        bool      `json:"is_archived"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertUserSession,
		arg.ID,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.IsRevoked,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
