// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, primary_email, display_name, profile_image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, google_id, primary_email, display_name, profile_image_url, is_archived, is_banned, is_muted, current_mode, is_seller_profile_approved, is_seller_profile_created, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID        string         `json:"google_id"`
	PrimaryEmail    string         `json:"primary_email"`
	DisplayName     sql.NullString `json:"display_name"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.GoogleID,
		arg.PrimaryEmail,
		arg.DisplayName,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.IsArchived,
		&i.IsBanned,
		&i.IsMuted,
		&i.CurrentMode,
		&i.IsSellerProfileApproved,
		&i.IsSellerProfileCreated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, primary_email, display_name, profile_image_url, is_archived, is_banned, is_muted, current_mode, is_seller_profile_approved, is_seller_profile_created, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.IsArchived,
		&i.IsBanned,
		&i.IsMuted,
		&i.CurrentMode,
		&i.IsSellerProfileApproved,
		&i.IsSellerProfileCreated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, google_id, primary_email, display_name, profile_image_url, is_archived, is_banned, is_muted, current_mode, is_seller_profile_approved, is_seller_profile_created, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.PrimaryEmail,
			&i.DisplayName,
			&i.ProfileImageUrl,
			&i.IsArchived,
			&i.IsBanned,
			&i.IsMuted,
			&i.CurrentMode,
			&i.IsSellerProfileApproved,
			&i.IsSellerProfileCreated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
