// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_refresh_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deprecateRefreshTokenByID = `-- name: DeprecateRefreshTokenByID :exec
UPDATE user_refresh_tokens
SET
  is_deprecated     = $2,
  deprecated_reason = $3,
  deprecated_at     = $4
WHERE id = $1
`

type DeprecateRefreshTokenByIDParams struct {
	ID               uuid.UUID      `json:"id"`
	IsDeprecated     bool           `json:"is_deprecated"`
	DeprecatedReason sql.NullString `json:"deprecated_reason"`
	DeprecatedAt     sql.NullTime   `json:"deprecated_at"`
}

func (q *Queries) DeprecateRefreshTokenByID(ctx context.Context, arg DeprecateRefreshTokenByIDParams) error {
	_, err := q.db.ExecContext(ctx, deprecateRefreshTokenByID,
		arg.ID,
		arg.IsDeprecated,
		arg.DeprecatedReason,
		arg.DeprecatedAt,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
  id,
  user_id,
  session_id,
  token_hash,
  deprecated_reason,
  is_deprecated,
  deprecated_at,
  expires_at,
  created_at
FROM user_refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (UserRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.DeprecatedReason,
		&i.IsDeprecated,
		&i.DeprecatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO user_refresh_tokens (
  id, user_id, session_id, token_hash,
  deprecated_reason, is_deprecated, deprecated_at,
  expires_at, created_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9
)
`

type InsertRefreshTokenParams struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	SessionID        uuid.UUID      `json:"session_id"`
	TokenHash        string         `json:"token_hash"`
	DeprecatedReason sql.NullString `json:"deprecated_reason"`
	IsDeprecated     bool           `json:"is_deprecated"`
	DeprecatedAt     sql.NullTime   `json:"deprecated_at"`
	ExpiresAt        time.Time      `json:"expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.TokenHash,
		arg.DeprecatedReason,
		arg.IsDeprecated,
		arg.DeprecatedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
