// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_mode_history.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertUserModeSwitchLog = `-- name: InsertUserModeSwitchLog :exec
INSERT INTO user_mode_history (
  id, user_id, from_mode, to_mode, switched_at
) VALUES (
  $1, $2, $3, $4, $5
)
`

type InsertUserModeSwitchLogParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	FromMode   string    `json:"from_mode"`
	ToMode     string    `json:"to_mode"`
	SwitchedAt time.Time `json:"switched_at"`
}

func (q *Queries) InsertUserModeSwitchLog(ctx context.Context, arg InsertUserModeSwitchLogParams) error {
	_, err := q.db.ExecContext(ctx, insertUserModeSwitchLog,
		arg.ID,
		arg.UserID,
		arg.FromMode,
		arg.ToMode,
		arg.SwitchedAt,
	)
	return err
}
